### ISSUE TITLE
update docs to mention disabling ad blocker

### ISSUE THREAD

**Issue by TylerLeonhardt** [bradoyler/xmr-miner#5]
I got this issue when first loading the demo:

```
bradoyler.github.io/:7 GET https://authedmine.com/lib/authedmine.min.js net::ERR_BLOCKED_BY_CLIENT
main.js:8 Uncaught ReferenceError: CoinHive is not defined
    at Object.<anonymous> (main.js:8)
    at e (bootstrap 861f4ece923278967c50:19)
    at bootstrap 861f4ece923278967c50:62
    at bootstrap 861f4ece923278967c50:62
```

It wasn't obvious but I needed to turn off my ad blocker. Maybe mention in the README about ad blockers?

**Comment by bradoyler** [comment]
@tylerl0706 will do. Thx!

**Comment by bradoyler** [comment]
https://github.com/bradoyler/xmr-miner/commit/4b0b236fbbd3de9f048ce45a0ff26e78f4bf2e9f#diff-04c6e90faac2675aa89e2176d2eec7d8R5
